services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - PG_HOST=db
    networks:
      - private_net
    depends_on:
      - db

    command: sh -c "python src/application/manage.py makemigrations && python src/application/manage.py migrate && python src/application/manage.py runserver 0.0.0.0:8000"

  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - private_net

networks:
  private_net:
    driver: bridge
